version: 2.1
jobs:
  test:
    parameters:
      elixir:
        type: string
    docker:
      - image: circleci/elixir:<< parameters.elixir >>
    steps:
      - checkout
      - run: mix deps.unlock --all
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
  format:
    docker:
      - image: circleci/elixir:latest
    steps:
      - checkout
      - run: mix format --check-formatted
workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              elixir:
                - '1.6'
                - '1.7'
                - '1.8'
                - '1.9'
                - '1.10'
  format:
    jobs:
      - format
