version: 2.1
jobs:
  analyze and test:
    parameters:
      elixir:
        type: string
    docker:
      - image: circleci/elixir:<< parameters.elixir >>
    steps:
      - checkout
      - run: mix deps.unlock --all
      - run: mix local.hex --force
      - restore_cache:
          keys:
            - mix-cache-{{ arch }}-<< parameters.elixir >>-{{ .Branch }}-{{ .Revision }}
            - mix-cache-{{ arch }}-<< parameters.elixir >>-{{ .Branch }}-
            - mix-cache-{{ arch }}-<< parameters.elixir >>
      - run: mix deps.get
      - save_cache:
          key: mix-cache-{{ arch }}-<< parameters.elixir >>-{{ .Branch }}-{{ .Revision }}-{{ checksum "mix.lock" }}
          paths: deps
      - restore_cache:
          keys:
            - build-cache-{{ arch }}-<< parameters.elixir >>-{{ .Branch }}-{{ .Revision }}
            - build-cache-{{ arch }}-<< parameters.elixir >>-{{ .Branch }}
            - build-cache-{{ arch }}-<< parameters.elixir >>
      - run: mix dialyzer
      - run: find _build/ -type f | xargs crc32 | sort > /tmp/_build.sum
      - save_cache:
          key: build-cache-{{ arch }}-<< parameters.elixir >>-{{ .Branch }}-{{ .Revision }}-{{ checksum "/tmp/_build.sum" }}
          paths: _build
      - run: mix test --cover --formatter JUnitFormatter
      - store_test_results:
          path: _build/test/lib/cloudinary
      - store_artifacts:
          path: cover
  format:
    docker:
      - image: circleci/elixir:latest
    steps:
      - checkout
      - run: mix format --check-formatted
workflows:
  analyze and test:
    jobs:
      - analyze and test:
          matrix:
            parameters:
              elixir:
                - '1.6'
                - '1.7'
                - '1.8'
                - '1.9'
                - '1.10'
  format:
    jobs:
      - format
