version: 2.1
jobs:
  test and analyze:
    parameters:
      elixir:
        type: string
    docker:
      - image: circleci/elixir:<< parameters.elixir >>
    steps:
      - checkout
      - run: mix deps.unlock --all
      - run: mix local.hex --force
      - restore_cache:
          keys:
            - mix-cache-<< parameters.elixir >>-{{ .Branch }}
            - mix-cache-<< parameters.elixir >>
      - run: mix deps.get
      - save_cache:
          key: mix-cache-<< parameters.elixir >>-{{ .Branch }}
          paths: deps
      - restore_cache:
          keys:
            - build-cache-<< parameters.elixir >>-{{ .Branch }}
            - build-cache-<< parameters.elixir >>
      - run: mix dialyzer
      - save_cache:
          key: build-cache-<< parameters.elixir >>-{{ .Branch }}
          paths: _build
      - run: mix test
  format:
    docker:
      - image: circleci/elixir:latest
    steps:
      - checkout
      - run: mix format --check-formatted
workflows:
  test and analyze:
    jobs:
      - test and analyze:
          matrix:
            parameters:
              elixir:
                - '1.6'
                - '1.7'
                - '1.8'
                - '1.9'
                - '1.10'
  format:
    jobs:
      - format
