defmodule Cloudinary.Transformation.Effect do
  @moduledoc """
  Representing `effect` parameter of transformation.
  ## Official documentation
  https://cloudinary.com/documentation/image_transformation_reference#effect_parameter
  https://cloudinary.com/documentation/video_transformation_reference#adding_video_effects
  """
  @type t ::
          __MODULE__.Accelerate.t()
          | __MODULE__.AdvRedeye.t()
          | __MODULE__.AntiRemoval.t()
          | __MODULE__.Art.t()
          | __MODULE__.AssistColorblind.t()
          | __MODULE__.AutoBrightness.t()
          | __MODULE__.AutoColor.t()
          | __MODULE__.AutoContrast.t()
          | __MODULE__.BackgroundRemoval.t()
          | __MODULE__.BlackWhite.t()
          | __MODULE__.Blue.t()
          | __MODULE__.Blur.t()
          | __MODULE__.BlurFaces.t()
          | __MODULE__.BlurRegion.t()
          | __MODULE__.Boomerang.t()
          | __MODULE__.Brightness.t()
          | __MODULE__.BrightnessHsb.t()
          | __MODULE__.Cartoonify.t()
          | __MODULE__.Colorize.t()
          | __MODULE__.Contrast.t()
          | __MODULE__.CutOut.t()
          | __MODULE__.Deshake.t()
          | __MODULE__.Displace.t()
          | __MODULE__.Distort.t()
          | __MODULE__.Fade.t()
          | __MODULE__.FillLight.t()
          | __MODULE__.Gamma.t()
          | __MODULE__.GradientFade.t()
          | __MODULE__.Grayscale.t()
          | __MODULE__.Green.t()
          | __MODULE__.Hue.t()
          | __MODULE__.Improve.t()
          | __MODULE__.Loop.t()
          | __MODULE__.MakeTransparent.t()
          | __MODULE__.Multiply.t()
          | __MODULE__.Negate.t()
          | __MODULE__.Noise.t()
          | __MODULE__.OilPaint.t()
          | __MODULE__.OpacityThreshold.t()
          | __MODULE__.OrderedDither.t()
          | __MODULE__.Outline.t()
          | __MODULE__.Overlay.t()
          | __MODULE__.Pixelate.t()
          | __MODULE__.PixelateFaces.t()
          | __MODULE__.PixelateRegion.t()
          | __MODULE__.Preview.t()
          | __MODULE__.Progressbar.t()
          | __MODULE__.Recolor.t()
          | __MODULE__.Red.t()
          | __MODULE__.Redeye.t()
          | __MODULE__.ReplaceColor.t()
          | __MODULE__.Reverse.t()
          | __MODULE__.Saturation.t()
          | __MODULE__.Screen.t()
          | __MODULE__.Sepia.t()
          | __MODULE__.Shadow.t()
          | __MODULE__.Sharpen.t()
          | __MODULE__.Shear.t()
          | __MODULE__.SimulateColorblind.t()
          | __MODULE__.StyleTransfer.t()
          | __MODULE__.Tint.t()
          | __MODULE__.Transition.t()
          | __MODULE__.Trim.t()
          | __MODULE__.UnsharpMask.t()
          | __MODULE__.Vectorize.t()
          | __MODULE__.Vibrance.t()
          | __MODULE__.ViesusCorrect.t()
          | __MODULE__.Vignette.t()
          | __MODULE__.Volume.t()
end
