defmodule Cloudinary.Transformation.EffectTest do
  use ExUnit.Case
  alias Cloudinary.Transformation.Effect
  doctest Effect.AdvRedeye
  doctest Effect.AntiRemoval
  doctest Effect.Art
  doctest Effect.AssistColorblind
  doctest Effect.AutoBrightness
  doctest Effect.AutoColor
  doctest Effect.AutoContrast
  doctest Effect.BackgroundRemoval
  doctest Effect.BlackWhite
  doctest Effect.Blue
  doctest Effect.Blur
  doctest Effect.BlurFaces
  doctest Effect.BlurRegion
  doctest Effect.Brightness
  doctest Effect.BrightnessHsb
  doctest Effect.Cartoonify
  doctest Effect.Colorize
  doctest Effect.Contrast
  doctest Effect.CutOut
  doctest Effect.Displace
  doctest Effect.Distort
  doctest Effect.Fade
  doctest Effect.FillLight
  doctest Effect.Gamma
  doctest Effect.GradientFade
  doctest Effect.Grayscale
  doctest Effect.Green
  doctest Effect.Hue
  doctest Effect.Improve
  doctest Effect.Loop
  doctest Effect.MakeTransparent
  doctest Effect.Multiply
  doctest Effect.Negate
  doctest Effect.OilPaint
  doctest Effect.OpacityThreshold
  doctest Effect.OrderedDither
  doctest Effect.Outline
  doctest Effect.Overlay
  doctest Effect.Pixelate
  doctest Effect.PixelateFaces
  doctest Effect.PixelateRegion
  doctest Effect.Recolor
  doctest Effect.Red
  doctest Effect.Redeye
  doctest Effect.ReplaceColor
  doctest Effect.Saturation
  doctest Effect.Screen
  doctest Effect.Sepia
  doctest Effect.Shadow
  doctest Effect.Sharpen
  doctest Effect.Shear
  doctest Effect.SimulateColorblind
  doctest Effect.StyleTransfer
  doctest Effect.Tint
  doctest Effect.Trim
  doctest Effect.UnsharpMask
  doctest Effect.Vectorize
  doctest Effect.Vibrance
  doctest Effect.ViesusCorrect
  doctest Effect.Vignette
end
